steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/cool-keel-408219/zainab-100948833:$COMMIT_SHA', '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/cool-keel-408219/zainab-100948833:$COMMIT_SHA']

images:
  - 'gcr.io/cool-keel-408219/zainab-100948833:$COMMIT_SHA'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
