steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/zainab-100948833/zainab-100948833:$COMMIT_SHA', '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/zainab-100948833/zainab-100948833:$COMMIT_SHA']

images:
  - 'gcr.io/zainab-100948833/zainab-100948833:$COMMIT_SHA'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  serviceAccount: id-51672872889-cloudbuild-gser@cool-keel-408219.iam.gserviceaccount.com
